### ISSUE TITLE
Support .Net Core App

### ISSUE THREAD

**Issue by itaibh** [adriangodong/githubjwt#1]
Hi @adriangodong,

I just tried changing the target framework of your library to `netcoreapp2.0` and ran the tests. They passed.
Any reason why you didn't do it in the first place? Is there a problem supporting netcoreapp?

From the build logs of https://github.com/octokit/octokit.net/pull/1738 it seems it can't restore your nuget and thus the build fails. I think if the nuget would support the .Net Core App target the build would pass.

What do you think?

**Comment by ryangribble** [comment]
being a library, this should be fine to target `netstandard` rather than `netcoreapp` which is for executables and test projects.  I dont think the issues on octokit need a change here (it's working locally for me as is, just not in appveyor/travisCI but im working on it!)

**Comment by itaibh** [comment]
Thanks, @ryangribble !

**Comment by adriangodong** [comment]
@ryangribble is correct. The library should target netstandard (1.x / 2.0) but the test project should target netcoreapp (1.0 / 1.1 / 2.0).

An earlier question was whether we can downversion the library to netstandard 1.x. I managed to successfully compile to target netstandard 1.4 and was able to test correctly on netcoreapp1.1. Will it help if I spend some time on this?

**Comment by ryangribble** [comment]
I don't really have a problem moving octokit tests forward to 2.0

Interested how you did it though! I had a play with your library to see if I could send a PR (before I concluded moving octokit tests to 2.0 was the best option) and apart from that SilverGiggle dependency which would also have had to be downgraded I found some of the crypto stuff in bouncy castle actually threw platform not implemented exceptions on anything pre 2.0 so figured it was a no go?

**Comment by ryangribble** [comment]
Hmm so Im not sure what was wrong when I tried to do this, because when I pull down your PR I find I can build and run the tests just fine 🤷‍♂️

**Comment by adriangodong** [comment]
I’m pretty sure that’s what I had too, hence targeted to 2.0. Seems like a patch to 1.1 added the implementation.

**Comment by ryangribble** [comment]
I tried netcoreapp1.0 and netcoreapp1.1 and had the issue on both. Maybe something was cached or something, when I tried 1.1

Anyway it seems to work now!
