### ISSUE TITLE
IAT Time synchronization issue

### ISSUE THREAD

**Issue by Hdom** [adriangodong/githubjwt#60]
Hello, I am getting error 

`'Issued at' claim ('iat') must be an Integer representing the time that the assertion was issued`

When attempting to use the JwtToken generated by GitHubJwtFactory.CreateEncodedJwtToken method.

I believe this is some sort of time synchronization issue between the client and the server (github). 

I have found that adding 12 seconds of sleep between Token creation and usage solves the problem.

A solution would be to add an overload to allow an offset to be provided for the IAT.

**Comment by jjnguy** [comment]
I found that sleeping for just 5ms was enough to fix the issue.

**Comment by adriangodong** [comment]
@Hdom If you can, please create a Pull Request so we can merge it!

**Comment by Hdom** [comment]
@jjnguy Yeah it would depend on the magnitude of the time desync.

@adriangodong I have created #65 let me know if would would prefer a separate overload instead of an optional parameter.

**Comment by adriangodong** [comment]
#65 has been merged and released as [0.0.6](https://www.nuget.org/packages/GitHubJwt/0.0.6).
